[package]
name = "asura"
version = "0.1.0"
edition = "2021"

[dependencies]
# 2025 年 11 月 25 日のリビジョン
alacritty_terminal = { git = "https://github.com/alacritty/alacritty.git", rev = "52031ea" }

itertools = "0.14"
parking_lot = "*"
uuid = { version = "*", features = ["v4", "v7"] }

[dev-dependencies]
eframe = "0.31.1"
