[package]
name = "shaka"
version = "0.1.0"
edition = "2024"

[dependencies]
# 2025 年 1 月 15 日のリビジョン
alacritty_terminal = { git = "https://github.com/alacritty/alacritty.git", rev = "5e78d20" }

asura = { path = "../asura" }
ash = { workspace = true }
ash-window = { workspace = true }
crossfont = { workspace = true }
raw-window-handle = "0.6.0"
serde = { version = "1.0.104", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
winit = "0.30"
