[package]
name = "shaka"
version = "0.1.0"
edition = "2024"

[dependencies]
asura = { path = "../asura" }
renge = { path = "../renge" }

ash = { workspace = true }
ash-window = { workspace = true }
crossfont = { workspace = true }
wasmtime = "*"
raw-window-handle = "0.6.0"
tokio = { version = "1", features = ["full"] }
winit = { version = "0.30" }
