[package]
name = "shaka"
version = "0.1.0"
edition = "2024"

[dependencies]
asura = { path = "../asura" }
renge = { path = "../renge" }

ash = { workspace = true }
ash-window = { workspace = true }
font-kit = "0.14"
pathfinder_geometry = "*"
num-integer = "0.1"
wasmtime = "*"
raw-window-handle = "0.6.0"
tokio = { workspace = true }
winit = { version = "0.30" }
