[package]
name = "shalacritty"
version = "0.1.0"
edition = "2021"
rust-version = "1.73"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asura = { path = "../asura" }
profiler_core = { path = "../profiler_core" }
term-gfx = { path = "../term-gfx" }

# 2025 年 1 月 15 日のリビジョン
alacritty_terminal = { git = "https://github.com/alacritty/alacritty.git", rev = "5e78d20" }

ash = { workspace = true }
ash-window = { workspace = true }
bytemuck = { version = "*", features = ["derive"] }
clap = { version = "4.4.18", features = ["derive"] }
copypasta = "*"
crossfont = { workspace = true }
futures = { version = "0.3.31" }
image = "0.24.7"
nalgebra = "0.32.3"
notify = { version = "5.0.0-pre.16" }
pin-project = "1"
raw-window-handle = "0.6.0"
serde = { version = "1.0.104", features = ["derive"] }
toml = { version = "0.8.6" }
tokio = { version = "1", features = ["full"] }
tokio-stream = "*"
uuid = { version = "1.4.1", features = ["v4", "macro-diagnostics"] }
winit = "0.30"

wgpu = { version = "22.0.0", features = ["vulkan-portability"] }

# デバッグ用に利用するクレート
# TODO: 可能な限り optional にしたい
console-subscriber = "*"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-chrome = "0.7.2"

[build-dependencies]
bytemuck = { version = "*", features = ["derive"] }
naga = { version = "0.20.0", features = ["spv-in", "wgsl-out"] }

[dev-dependencies]
bmp = "*"

[features]
# トレーシングを有効にしたいときに指定します
# 有効にすると、アプリの終了時にトレーシング結果を chrome://tracing で利用できる json ファイル形式で出力します
tracing = []

# tokio-console での可視化を有効化する設定
tokio-subscriber = []
