// tonic のサンプルをとりあえずコピペ

syntax = "proto3";

package profile_core;

// プロファイル一覧を取得するリクエスト
message ProfileListRequest {
    repeated uint64 id_list = 1;
}

// プロファイル一覧の識別子
message ProfileListResponse {
    repeated uint64 id_list = 1;
}

message ProfileRequest {
    repeated uint64 id_list = 1;
}

message ProfileResponse {
    repeated string message = 1;
}

// Echo is the echo service.
service Profile {
    rpc RequestProfileList(ProfileListRequest) returns (ProfileListResponse) {}

    rpc RequestProfile(ProfileRequest) returns (ProfileResponse) {}
}
