[package]
name = "term-gfx"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { workspace = true }
ash-window = { workspace = true }
bytemuck = "*"
crossfont = { workspace = true }
naga = { version = "23.1.0", features = ["glsl-in", "spv-in", "spv-out"] }
raw-window-handle = "0.6.0"
wgpu = "23.0"

# backend のインスタンスを辞書として管理するための ID として利用
# 将来的に配列管理に移行するか、管理のデータ構造を選択できるようにして、
# uuid に依存しないようにしたい
uuid = {version = "*", features = ["v4"] }

[dev-dependencies]
bmp = "*"
naga = { version = "23.1.0", features = ["glsl-in", "spv-out"] }
winit = "0.30"

[build-dependencies]
naga = { version = "23.1.0", features = ["glsl-in", "spv-out"] }
